### PR TITLE
fix: input not being initialized on simple resource modal

### PR DESCRIPTION
**Pull request by saade**
it was not working on modals

### CODE REVIEW

**Comment by RVxLab** [comment]
Adding this will essentially call the initialize event twice, which is not necessarily what you want.

Perhaps it's a good idea to replace the eventlistener with a `$nextTick` call or add the `{ once: true }` option.

**Comment by saade** [comment]
Will call it twice, but will not render the first time because the HTML (input) is not in the DOM, so i don't see as a problem.

But anyway, can you fix that?

**Comment by RVxLab** [comment]
Thank you very much for the report and the PR. You can ignore the commit I made to the fork, the GitHub CLI tool didn't work how I expected it to.

**Comment by saade** [comment]
Do you mind entering the Filament Discord? People are asking questions and reporting bugs on your plugin channel.

https://discord.gg/uBDDAY4Z

**Pull request merged**
